### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by llynnjrtt** [RasaHQ/rasa-nlu-examples#165]
Hi,
I am tried to use rasaHQ ThaiTokenizer, and wanted to apply the  component rasa_nlu_examples.tokenizers.ThaiTokenizer.
this is my Configuration files : 
```
language: th
pipeline:
  - name: rasa_nlu_examples.tokenizers.ThaiTokenizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 100

policies:
  - name: MemoizationPolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 100
    constrain_similarities: true
  - name: RulePolicy
```

Then I installed  this command 

`pip install "rasa_nlu_examples[thai] @ https://github.com/RasaHQ/rasa-nlu-examples.git"`

and when I trained using `rasa train` it gives me this error 

```
/Users/llynnjrt/rasa_test2/venv/lib/python3.7/site-packages/rasa/engine/recipes/recipe.py:35: FutureWarning: From Rasa Open Source 4.0.0 onwards it will be required to specify a recipe in your model configuration. Defaulting to recipe 'default.v1'.
  "From Rasa Open Source 4.0.0 onwards it will be required to specify "
Traceback (most recent call last):
  File "/Users/llynnjrt/rasa_test2/venv/bin/rasa", line 8, in <module>
    sys.exit(main())
  File "/Users/llynnjrt/rasa_test2/venv/lib/python3.7/site-packages/rasa/__main__.py", line 121, in main
    cmdline_arguments.func(cmdline_arguments)
  File "/Users/llynnjrt/rasa_test2/venv/lib/python3.7/site-packages/rasa/cli/train.py", line 59, in <lambda>
    train_parser.set_defaults(func=lambda args: run_training(args, can_exit=True))
  File "/Users/llynnjrt/rasa_test2/venv/lib/python3.7/site-packages/rasa/cli/train.py", line 103, in run_training
    finetuning_epoch_fraction=args.epoch_fraction,
  File "/Users/llynnjrt/rasa_test2/venv/lib/python3.7/site-packages/rasa/api.py", line 117, in train
    finetuning_epoch_fraction=finetuning_epoch_fraction,
  File "/Users/llynnjrt/rasa_test2/venv/lib/python3.7/site-packages/rasa/model_training.py", line 181, in train
    **(nlu_additional_arguments or {}),
  File "/Users/llynnjrt/rasa_test2/venv/lib/python3.7/site-packages/rasa/model_training.py", line 213, in _train_graph
    config, kwargs, training_type=training_type, is_finetuning=is_finetuning
  File "/Users/llynnjrt/rasa_test2/venv/lib/python3.7/site-packages/rasa/engine/recipes/default_recipe.py", line 192, in graph_config_for_recipe
    train_nodes, preprocessors = self._create_train_nodes(config, cli_parameters)
  File "/Users/llynnjrt/rasa_test2/venv/lib/python3.7/site-packages/rasa/engine/recipes/default_recipe.py", line 243, in _create_train_nodes
    train_config, train_nodes, cli_parameters
  File "/Users/llynnjrt/rasa_test2/venv/lib/python3.7/site-packages/rasa/engine/recipes/default_recipe.py", line 278, in _add_nlu_train_nodes
    component = self._from_registry(component_name)
  File "/Users/llynnjrt/rasa_test2/venv/lib/python3.7/site-packages/rasa/engine/recipes/default_recipe.py", line 147, in _from_registry
    clazz = rasa.shared.utils.common.class_from_module_path(name)
  File "/Users/llynnjrt/rasa_test2/venv/lib/python3.7/site-packages/rasa/shared/utils/common.py", line 36, in class_from_module_path
    m = importlib.import_module(module_name)
  File "/usr/local/Cellar/python@3.7/3.7.12_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'rasa_nlu_examples'
```

**Comment by koaning** [comment]
Can you confirm that you installed this package? You can verify by running: 

```
python -m pip freeze | rasa-nlu-examples
```
