### ISSUE TITLE
Installation not working

### ISSUE THREAD

**Issue by deteixeira** [RasaHQ/rasa-nlu-examples#169]
Hi, thank you all for this project.
I am trying to download this project but it returns the following error:

ERROR: Could not find a version that satisfies the requirement rasa~=3.0.0 (from rasa-nlu-examples) (from versions: 0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.0.5, 0.1.0, 0.1.1, 0.2.0a2, 0.2.0a3, 0.14.0a5, 0.14.0a6, 0.14.0a7, 0.14.0a8, 0.14.0a9, 0.15.0a6, 1.0.0a1, 1.0.0a2, 1.0.0a3, 1.0.0a4, 1.0.0a5, 1.0.0rc1, 1.0.0rc2, 1.0.0rc3, 1.0.0rc4, 1.0.0rc5, 1.0.0rc6, 1.0.0rc7, 1.0.0rc8, 1.0.0rc9, 1.0.0rc10, 1.0.0rc11, 1.0.0rc12, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6, 1.0.7, 1.0.8, 1.0.9, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5, 1.1.6, 1.1.7, 1.1.8, 1.2.0a2, 1.2.0a3, 1.2.0a4, 1.2.0a5, 1.2.0a6, 1.2.0a7, 1.2.0, 1.2.1, 1.2.2, 1.2.3, 1.2.4, 1.2.5, 1.2.6, 1.2.7, 1.2.8, 1.2.9, 1.2.10, 1.2.11, 1.2.12, 1.3.0a1, 1.3.0a2, 1.3.0, 1.3.1a1, 1.3.1a3, 1.3.1a4, 1.3.1a5, 1.3.1a8, 1.3.1a10, 1.3.1a11, 1.3.1a12, 1.3.1a14, 1.3.1, 1.3.2, 1.3.3, 1.3.4, 1.3.6, 1.3.7, 1.3.8, 1.3.9, 1.3.10, 1.4.0, 1.4.1, 1.4.2, 1.4.3, 1.4.4, 1.4.5, 1.4.6, 1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.6.0a1, 1.6.0a2, 1.6.0, 1.6.1, 1.6.2, 1.7.0, 1.7.1, 1.7.2, 1.7.3, 1.7.4, 1.8.0, 1.8.1, 1.8.2, 1.8.3, 1.9.0, 1.9.1, 1.9.2, 1.9.3, 1.9.4, 1.9.5, 1.9.6, 1.9.7, 1.10.0a1, 1.10.0a2, 1.10.0, 1.10.1, 1.10.2, 3.1.0, 3.1.1, 3.1.2, 3.1.3, 3.1.4, 3.1.5, 3.1.6, 3.2.0, 3.2.1, 3.2.2, 3.2.4, 3.2.5)
ERROR: No matching distribution found for rasa~=3.0.0

However, when I check the rasa --version it returns the following:

Rasa Version      :         3.1.0
Minimum Compatible Version: 3.0.0
Rasa SDK Version  :         3.1.1
Rasa X Version    :         None
Python Version    :         3.9.7
Operating System  :         Windows-10-10.0.19043-SP0

Can someone help me?
Thanks in advance

**Comment by ninhduyhuy24022001** [comment]
you can try python 3.8

**Comment by shreyashgupta68** [comment]
python version is the main cause for this
use python version 3.7 or 3.8

**Comment by hrabkin** [comment]
With 3.7.17

```
Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [55 lines of output]
      running dist_info
      creating /private/var/folders/22/qxr_sbhx0v525gj1309w1vgc0000gn/T/pip-modern-metadata-ysl9mml3/gensim.egg-info
      writing /private/var/folders/22/qxr_sbhx0v525gj1309w1vgc0000gn/T/pip-modern-metadata-ysl9mml3/gensim.egg-info/PKG-INFO
      writing dependency_links to /private/var/folders/22/qxr_sbhx0v525gj1309w1vgc0000gn/T/pip-modern-metadata-ysl9mml3/gensim.egg-info/dependency_links.txt
      writing requirements to /private/var/folders/22/qxr_sbhx0v525gj1309w1vgc0000gn/T/pip-modern-metadata-ysl9mml3/gensim.egg-info/requires.txt
      writing top-level names to /private/var/folders/22/qxr_sbhx0v525gj1309w1vgc0000gn/T/pip-modern-metadata-ysl9mml3/gensim.egg-info/top_level.txt
      writing manifest file '/private/var/folders/22/qxr_sbhx0v525gj1309w1vgc0000gn/T/pip-modern-metadata-ysl9mml3/gensim.egg-info/SOURCES.txt'
      Traceback (most recent call last):
        File "/Users/**/.pyenv/versions/3.7.17/lib/python3.7/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/**/.pyenv/versions/3.7.17/lib/python3.7/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/**/.pyenv/versions/3.7.17/lib/python3.7/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "/private/var/folders/22/qxr_sbhx0v525gj1309w1vgc0000gn/T/pip-build-env-hwb0kcpr/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 380, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/private/var/folders/22/qxr_sbhx0v525gj1309w1vgc0000gn/T/pip-build-env-hwb0kcpr/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 488, in run_setup
          self).run_setup(setup_script=setup_script)
        File "/private/var/folders/22/qxr_sbhx0v525gj1309w1vgc0000gn/T/pip-build-env-hwb0kcpr/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 421, in <module>
        File "/private/var/folders/22/qxr_sbhx0v525gj1309w1vgc0000gn/T/pip-build-env-hwb0kcpr/overlay/lib/python3.7/site-packages/setuptools/__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
        File "/private/var/folders/22/qxr_sbhx0v525gj1309w1vgc0000gn/T/pip-build-env-hwb0kcpr/overlay/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/private/var/folders/22/qxr_sbhx0v525gj1309w1vgc0000gn/T/pip-build-env-hwb0kcpr/overlay/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/private/var/folders/22/qxr_sbhx0v525gj1309w1vgc0000gn/T/pip-build-env-hwb0kcpr/overlay/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/private/var/folders/22/qxr_sbhx0v525gj1309w1vgc0000gn/T/pip-build-env-hwb0kcpr/overlay/lib/python3.7/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/private/var/folders/22/qxr_sbhx0v525gj1309w1vgc0000gn/T/pip-build-env-hwb0kcpr/overlay/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/private/var/folders/22/qxr_sbhx0v525gj1309w1vgc0000gn/T/pip-build-env-hwb0kcpr/overlay/lib/python3.7/site-packages/setuptools/command/dist_info.py", line 99, in run
          self.egg_info.run()
        File "/private/var/folders/22/qxr_sbhx0v525gj1309w1vgc0000gn/T/pip-build-env-hwb0kcpr/overlay/lib/python3.7/site-packages/setuptools/command/egg_info.py", line 314, in run
          self.find_sources()
        File "/private/var/folders/22/qxr_sbhx0v525gj1309w1vgc0000gn/T/pip-build-env-hwb0kcpr/overlay/lib/python3.7/site-packages/setuptools/command/egg_info.py", line 322, in find_sources
          mm.run()
        File "/private/var/folders/22/qxr_sbhx0v525gj1309w1vgc0000gn/T/pip-build-env-hwb0kcpr/overlay/lib/python3.7/site-packages/setuptools/command/egg_info.py", line 551, in run
          self.add_defaults()
        File "/private/var/folders/22/qxr_sbhx0v525gj1309w1vgc0000gn/T/pip-build-env-hwb0kcpr/overlay/lib/python3.7/site-packages/setuptools/command/egg_info.py", line 589, in add_defaults
          sdist.add_defaults(self)
        File "/private/var/folders/22/qxr_sbhx0v525gj1309w1vgc0000gn/T/pip-build-env-hwb0kcpr/overlay/lib/python3.7/site-packages/setuptools/command/sdist.py", line 104, in add_defaults
          super().add_defaults()
        File "/private/var/folders/22/qxr_sbhx0v525gj1309w1vgc0000gn/T/pip-build-env-hwb0kcpr/overlay/lib/python3.7/site-packages/setuptools/_distutils/command/sdist.py", line 251, in add_defaults
          self._add_defaults_ext()
        File "/private/var/folders/22/qxr_sbhx0v525gj1309w1vgc0000gn/T/pip-build-env-hwb0kcpr/overlay/lib/python3.7/site-packages/setuptools/_distutils/command/sdist.py", line 335, in _add_defaults_ext
          build_ext = self.get_finalized_command('build_ext')
        File "/private/var/folders/22/qxr_sbhx0v525gj1309w1vgc0000gn/T/pip-build-env-hwb0kcpr/overlay/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 305, in get_finalized_command
          cmd_obj.ensure_finalized()
        File "/private/var/folders/22/qxr_sbhx0v525gj1309w1vgc0000gn/T/pip-build-env-hwb0kcpr/overlay/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 111, in ensure_finalized
          self.finalize_options()
        File "<string>", line 111, in finalize_options
      AttributeError: 'dict' object has no attribute '__NUMPY_SETUP__'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by Mahran-xo** [comment]
i have the same problem too
