### ISSUE TITLE
Error initializing graphComponent with GensimFeaturizer

### ISSUE THREAD

**Issue by deteixeira** [RasaHQ/rasa-nlu-examples#170]
Hi everyone,
I was trying to use word2vec model with the Google News dataset in my chatbot:

   - name: WhitespaceTokenizer
   - name: LexicalSyntacticFeaturizer
   - name: CountVectorsFeaturizer
     analyzer: char_wb
     min_ngram: 1
     max_ngram: 4
   - name: rasa_nlu_examples.featurizers.dense.GensimFeaturizer
     cache_path: word2vec/GoogleNews-vectors-negative300.bin
   - name: DIETClassifier
     epochs: 100

However, it is returning the following error what I do -rasa train:
2022-08-22 00:14:07 INFO     rasa.engine.training.hooks  - Restored component 'LexicalSyntacticFeaturizer' from cache.
2022-08-22 00:14:07 INFO     rasa.engine.training.hooks  - Restored component 'CountVectorsFeaturizer' from cache.
2022-08-22 00:14:07 INFO     rasa.engine.training.hooks  - Restored component 'MemoizationPolicy' from cache.
2022-08-22 00:14:07 INFO     rasa.engine.training.hooks  - Restored component 'RulePolicy' from cache.
2022-08-22 00:14:07 INFO     rasa.engine.training.hooks  - Restored component 'TEDPolicy' from cache.
2022-08-22 00:14:08 INFO     gensim.utils  - loading Word2VecKeyedVectors object from word2vec/GoogleNews-vectors-negative300.bin
Traceback (most recent call last):                                                                                                          
  File "C:\Users\debor\anaconda3\envs\bot2\lib\site-packages\rasa\engine\graph.py", line 398, in _load_component                            
    **kwargs,                                                                                                                               
  File "C:\Users\debor\anaconda3\envs\bot2\lib\site-packages\rasa\engine\graph.py", line 219, in load                                       
    return cls.create(config, model_storage, resource, execution_context)                                                                   
  File "C:\Users\debor\anaconda3\envs\bot2\lib\site-packages\rasa_nlu_examples\featurizers\dense\gensim_featurizer.py", line 71, in create  
    return cls(config, execution_context.node_name)                                                                                         
  File "C:\Users\debor\anaconda3\envs\bot2\lib\site-packages\rasa_nlu_examples\featurizers\dense\gensim_featurizer.py", line 60, in __init__
    self.kv = KeyedVectors.load(config["cache_path"])                                                                                       
  File "C:\Users\debor\anaconda3\envs\bot2\lib\site-packages\gensim\models\keyedvectors.py", line 1553, in load                             
    model = super(WordEmbeddingsKeyedVectors, cls).load(fname_or_handle, **kwargs)                                                          
  File "C:\Users\debor\anaconda3\envs\bot2\lib\site-packages\gensim\models\keyedvectors.py", line 228, in load                              
    return super(BaseKeyedVectors, cls).load(fname_or_handle, **kwargs)                                                                     
  File "C:\Users\debor\anaconda3\envs\bot2\lib\site-packages\gensim\utils.py", line 435, in load
    obj = unpickle(fname)
  File "C:\Users\debor\anaconda3\envs\bot2\lib\site-packages\gensim\utils.py", line 1398, in unpickle
    return _pickle.load(f, encoding='latin1')
_pickle.UnpicklingError: invalid load key, '3'.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\debor\anaconda3\envs\bot2\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\debor\anaconda3\envs\bot2\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\debor\anaconda3\envs\bot2\Scripts\rasa.exe\__main__.py", line 7, in <module>
  File "C:\Users\debor\anaconda3\envs\bot2\lib\site-packages\rasa\__main__.py", line 121, in main
    cmdline_arguments.func(cmdline_arguments)
  File "C:\Users\debor\anaconda3\envs\bot2\lib\site-packages\rasa\cli\train.py", line 59, in <lambda>
    train_parser.set_defaults(func=lambda args: run_training(args, can_exit=True))
  File "C:\Users\debor\anaconda3\envs\bot2\lib\site-packages\rasa\cli\train.py", line 103, in run_training
    finetuning_epoch_fraction=args.epoch_fraction,
  File "C:\Users\debor\anaconda3\envs\bot2\lib\site-packages\rasa\api.py", line 117, in train
    finetuning_epoch_fraction=finetuning_epoch_fraction,
  File "C:\Users\debor\anaconda3\envs\bot2\lib\site-packages\rasa\model_training.py", line 181, in train
    **(nlu_additional_arguments or {}),
  File "C:\Users\debor\anaconda3\envs\bot2\lib\site-packages\rasa\model_training.py", line 242, in _train_graph
    is_finetuning=is_finetuning,
  File "C:\Users\debor\anaconda3\envs\bot2\lib\site-packages\rasa\engine\training\graph_trainer.py", line 108, in train
    graph_runner.run(inputs={PLACEHOLDER_IMPORTER: importer})
  File "C:\Users\debor\anaconda3\envs\bot2\lib\site-packages\rasa\engine\runner\dask.py", line 106, in run
    dask_result = dask.get(run_graph, run_targets)
  File "C:\Users\debor\anaconda3\envs\bot2\lib\site-packages\dask\local.py", line 565, in get_sync
    **kwargs
  File "C:\Users\debor\anaconda3\envs\bot2\lib\site-packages\dask\local.py", line 503, in get_async
    for key, res_info, failed in queue_get(queue).result():
  File "C:\Users\debor\anaconda3\envs\bot2\lib\concurrent\futures\_base.py", line 428, in result
    return self.__get_result()
  File "C:\Users\debor\anaconda3\envs\bot2\lib\concurrent\futures\_base.py", line 384, in __get_result
    raise self._exception
  File "C:\Users\debor\anaconda3\envs\bot2\lib\site-packages\dask\local.py", line 545, in submit
    fut.set_result(fn(*args, **kwargs))
  File "C:\Users\debor\anaconda3\envs\bot2\lib\site-packages\dask\local.py", line 237, in batch_execute_tasks
    return [execute_task(*a) for a in it]
  File "C:\Users\debor\anaconda3\envs\bot2\lib\site-packages\dask\local.py", line 237, in <listcomp>
    return [execute_task(*a) for a in it]
  File "C:\Users\debor\anaconda3\envs\bot2\lib\site-packages\dask\local.py", line 228, in execute_task
    result = pack_exception(e, dumps)
  File "C:\Users\debor\anaconda3\envs\bot2\lib\site-packages\dask\local.py", line 223, in execute_task
    result = _execute_task(task, data)
  File "C:\Users\debor\anaconda3\envs\bot2\lib\site-packages\dask\core.py", line 121, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "C:\Users\debor\anaconda3\envs\bot2\lib\site-packages\rasa\engine\graph.py", line 448, in __call__
    self._load_component(**constructor_kwargs)
  File "C:\Users\debor\anaconda3\envs\bot2\lib\site-packages\rasa\engine\graph.py", line 407, in _load_component
    ) from e
rasa.engine.exceptions.GraphComponentException: Error initializing graph component for node 'run_rasa_nlu_examples.featurizers.dense.GensimFeaturizer3'.

Attached, I have a file with what is happening when I run - rasa shell nlu --debug.
[error.txt](https://github.com/RasaHQ/rasa-nlu-examples/files/9390146/error.txt)

Can someone help me?

**Comment by shreyashgupta68** [comment]
Hi,
why are you using pickle?
